package com.android.launcher.dao;

import android.content.Context;

import com.android.launcher.entity.CheckBoxCarInfo;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.


public class CheckBoxCarInfoDaoUtil {

    private static final String TAG = CheckBoxCarInfoDao.class.getSimpleName();

    private DaoManager mManager;

    public CheckBoxCarInfoDaoUtil(Context context){
        mManager = DaoManager.getInstance();
        mManager.init(context);
    }

    /**
     * 完成记录的插入，如果表未创建，先创建表
     * @return
     */
    public boolean insert(CheckBoxCarInfo checkBoxCarInfo){
        boolean flag = false;
        flag = mManager.getDaoSession().insertOrReplace(checkBoxCarInfo) == -1 ? false : true;
        return flag;
    }

    /**
     *
     * 插入多条数据，在子线程操作
     *
     * @return
     */
    public boolean insertMult(final List<CheckBoxCarInfo> checkBoxEntities) {
        boolean flag = false;
        try {
            mManager.getDaoSession().runInTx(new Runnable() {
                @Override
                public void run() {
                    for (CheckBoxCarInfo checkBoxCarInfo : checkBoxEntities) {
//                        Log.i("aaaaa",song+"=======================");
                        mManager.getDaoSession().insert(checkBoxCarInfo);
                    }
                }
            });
            flag = true;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return flag;
    }


    /**
     * 删除所有记录
     */
    public void deleteAll(){
        boolean flag = false;
        try {
            //按照id删除
            mManager.getDaoSession().deleteAll(CheckBoxCarInfo.class);
            flag = true;
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    /**
     * 查询所有记录
     * @return
     */
    public List<CheckBoxCarInfo> queryAll(){
        return mManager.getDaoSession().loadAll(CheckBoxCarInfo.class);
    }

}
