package com.android.launcher.dao;

import android.content.Context;

import com.android.launcher.entity.MileStart;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "SONG".
*/
public class MileStartDaoUtil {

    private static final String TAG = MileStart.class.getSimpleName();
    // TODO: 2023-02-11 加锁 增删改查以后如果有其他线程需要加锁
    private DaoManager mManager;
    public MileStartDaoUtil(Context context){
        mManager = DaoManager.getInstance();
        mManager.init(context);
    }

    /**
     * 完成记录的插入，如果表未创建，先创建表
     * @return
     */
    public boolean insert(MileStart mileStart){
        boolean flag = false;
        flag = mManager.getDaoSession().insertOrReplace(mileStart) == -1 ? false : true;
        //   Log.i(TAG, "insert TestOrder :" + flag + "-->" + TestOrder.toString());
        return flag;
    }

    /**
     *
     * 插入多条数据，在子线程操作
     *
     * @return
     */
    public boolean insertMult(final List<MileStart> mileStarts) {
        boolean flag = false;
        try {
            mManager.getDaoSession().runInTx(new Runnable() {
                @Override
                public void run() {
                    for (MileStart mileStart : mileStarts) {
//                        Log.i("aaaaa",song+"=======================");
                        mManager.getDaoSession().insertOrReplace(mileStart);
                    }
                }
            });
            flag = true;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return flag;
    }


    /**
     * 删除所有记录
     */
    public void deleteAll(){
        boolean flag = false;
        try {
            //按照id删除
            mManager.getDaoSession().deleteAll(MileStart.class);
            flag = true;
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    /**
     * 查询所有记录
     * @return
     */
    public List<MileStart> queryAll(){
        return mManager.getDaoSession().loadAll(MileStart.class);
    }



    /**
     * 查询所有记录
     * @return
     */
    public MileStart queryMileStart(){
        return mManager.getDaoSession().queryBuilder(MileStart.class).limit(1).unique() ;
    }
}
