package com.android.launcher.dao;

import android.content.Context;

import com.android.launcher.entity.Param;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "SONG".
*/
public class ParamDaoUtil {

    private static final String TAG = SongDao.class.getSimpleName();

    private DaoManager mManager;

    public ParamDaoUtil(Context context){
        mManager = DaoManager.getInstance();
        mManager.init(context);
    }

    /**
     * 完成记录的插入，如果表未创建，先创建表
     * @return
     */
    public boolean insert(Param param){
        boolean flag = false;
        flag = mManager.getDaoSession().insert(param) == -1 ? false : true;
        //   Log.i(TAG, "insert TestOrder :" + flag + "-->" + TestOrder.toString());
        return flag;
    }

    /**
     * 更换
     * @param param
     * @return
     */
    public boolean update(Param param){
        boolean flag = false;
        flag = mManager.getDaoSession().insertOrReplace(param) == -1 ? false : true;
        //   Log.i(TAG, "insert TestOrder :" + flag + "-->" + TestOrder.toString());
        return flag;
    }
    /**
     *
     * 插入多条数据，在子线程操作
     *
     * @return
     */
    public boolean insertMult(final List<Param> params) {
        boolean flag = false;
        try {
            mManager.getDaoSession().runInTx(new Runnable() {
                @Override
                public void run() {
                    for (Param param : params) {
//                        Log.i("aaaaa",song+"=======================");
                        mManager.getDaoSession().insertOrReplace(param);
                    }
                }
            });
            flag = true;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return flag;
    }


    /**
     * 删除所有记录
     */
    public void deleteAll(){
        boolean flag = false;
        try {
            //按照id删除
            mManager.getDaoSession().deleteAll(Param.class);
            flag = true;
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    /**
     * 查询所有记录
     * @return
     */
    public List<Param> queryAll(){
        return mManager.getDaoSession().loadAll(Param.class);
    }



    /**
     * 查询所有记录
     * @return
     */
    public Param queryParam(){
        Param param =  mManager.getDaoSession().queryBuilder(Param.class).limit(1).unique();

        return param ;
    }

    /**
     * 根据paramName查询
     * @param ac
     * @return
     */
    public Param queryParamName(String ac) {
        return mManager.getDaoSession().queryBuilder(Param.class).where(ParamDao.Properties.ParamName.eq(ac)).unique() ;
    }
}
