package com.android.launcher.dao;

import android.content.Context;

import com.android.launcher.entity.MileSet;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "SONG".
*/
public class MileSetDaoUtil {

    private static final String TAG = MileSet.class.getSimpleName();

    private DaoManager mManager;

    public MileSetDaoUtil(Context context){
        mManager = DaoManager.getInstance();
        mManager.init(context);
    }

    /**
     * 完成记录的插入，如果表未创建，先创建表
     * @return
     */
    public boolean insert(MileSet mileSet){
        boolean flag = false;
        flag = mManager.getDaoSession().insertOrReplace(mileSet) == -1 ? false : true;
        //   Log.i(TAG, "insert TestOrder :" + flag + "-->" + TestOrder.toString());
        return flag;
    }

    /**
     *
     * 插入多条数据，在子线程操作
     *
     * @return
     */
    public boolean insertMult(final List<MileSet> mileSets) {
        boolean flag = false;
        try {
            mManager.getDaoSession().runInTx(new Runnable() {
                @Override
                public void run() {
                    for (MileSet mileSet : mileSets) {
//                        Log.i("aaaaa",song+"=======================");
                        mManager.getDaoSession().insertOrReplace(mileSet);
                    }
                }
            });
            flag = true;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return flag;
    }


    /**
     * 删除所有记录
     */
    public void deleteAll(){
        boolean flag = false;
        try {
            //按照id删除
            mManager.getDaoSession().deleteAll(MileSet.class);
            flag = true;
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    /**
     * 查询所有记录
     * @return
     */
    public List<MileSet> queryAll(){
        return mManager.getDaoSession().loadAll(MileSet.class);
    }



    /**
     * 查询所有记录
     * @return
     */
    public MileSet queryMileSet(){
        return mManager.getDaoSession().queryBuilder(MileSet.class).limit(1).unique() ;
    }
}
