package com.android.launcher.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.android.launcher.entity.MileSet;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MILE_SET".
*/
public class MileSetDao extends AbstractDao<MileSet, Long> {

    public static final String TABLENAME = "MILE_SET";

    /**
     * Properties of entity MileSet.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SetTime = new Property(1, String.class, "setTime", false, "SET_TIME");
        public final static Property SetMile = new Property(2, String.class, "setMile", false, "SET_MILE");
    }


    public MileSetDao(DaoConfig config) {
        super(config);
    }
    
    public MileSetDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MILE_SET\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SET_TIME\" TEXT," + // 1: setTime
                "\"SET_MILE\" TEXT);"); // 2: setMile
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MILE_SET\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MileSet entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String setTime = entity.getSetTime();
        if (setTime != null) {
            stmt.bindString(2, setTime);
        }
 
        String setMile = entity.getSetMile();
        if (setMile != null) {
            stmt.bindString(3, setMile);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MileSet entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String setTime = entity.getSetTime();
        if (setTime != null) {
            stmt.bindString(2, setTime);
        }
 
        String setMile = entity.getSetMile();
        if (setMile != null) {
            stmt.bindString(3, setMile);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MileSet readEntity(Cursor cursor, int offset) {
        MileSet entity = new MileSet( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // setTime
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // setMile
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MileSet entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSetTime(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSetMile(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MileSet entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MileSet entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MileSet entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
